### ISSUE TITLE
Platform to label the dataset.

### ISSUE THREAD

**Issue by polodealvarado** [ELS-RD/anonymisation#14]
Good morning.

First of all thank you so much for uploading your code, it is great for anyone who is starting to use Flair.

I would like to ask you what type of software/platform did you use to tag tokens.

**Comment by pommedeterresautee** [comment]
Hi, we are mainly using tag tog.
We have written on the subject here: https://towardsdatascience.com/benchmark-ner-algorithm-d4ab01b2d4c3

**Comment by polodealvarado** [comment]
Great, thank you so much.
